openapi: 3.0.1
info:
  title: WeatherDataPublishAPI
  description: API Definition of WeatherDataPublishAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/publishweatherdata
paths:
  /:
    post:
      responses:
        default:
          description: Default response
